version: '3.8'
services:
  backend:
    build:
      context: ./marketsage-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./marketsage-backend:/app
      - /app/node_modules # Prevent local node_modules override
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  frontend:
    build:
      context: ./marketsage-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./marketsage-frontend:/usr/share/nginx/html